TOP = ../..
include $(TOP)/configure/CONFIG

TARGETS = envPaths
SCRIPTS += ../stHexapodDemo.sh
SCRIPTS += envPaths
SCRIPTS += stHexapodDemo.boot

include $(TOP)/configure/RULES.ioc
include $(TOP)/configure/RULES

